language: ruby
rvm:
  - 2.2.0
env:
  global:
    secure: b1bOX2HSEnl17uKmuSoMTmwP7Y1YdnXf/P1UnNFme/Hb+BYdFrQNJTDl6VCj0Xg/0KKNDsb5NRgjRvlQ2HAp6RaLioM3yORsg+Pol4w7apX1A1ARa75L6OEFs8ZOvTg8swsn6KkqsuwYqfikcSvCllMYxOML38Ur5ulqzn/C++Y=
after_success:
  - "openssl aes-256-cbc -k '$DEPLOY_KEY' -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa"
  - "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production deploy"
