toolbar:
  "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent"
plugins:
  - image
  - imagetools
  - uploadimage
  - media
  - charmap
  - link
  - autolink
  - advlist
  - lists
  - hr
  - table
  - code
  - contextmenu
  - wordcount
  - preview
  - paste
  - insertdatetime
  - visualblocks
  - print
  - searchreplace
  - fullscreen
